services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=maker-menu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dimik2001.
    ports:
      - 5432:5432

  maker-menu:
    image: pizza-project/maker-menu:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"