server:
  port: 8083
spring:
  application:
    name: maker-menu
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testDB1
    password: sa
    username: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:db/scripts/data/import_*_data.sql
  liquibase:
    change-log: classpath:db/migrations/h2-changeLog.xml

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/maker-menu
    username: postgres
    password: Dimik2001.
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migrations/postgres-changelog.xml